version: '3.7'

services:
  app:
    build: .
    container_name: sesc-escola
    #entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 timeout 40s ./.docker/entrypoint.sh
    enviroment:
      -_DB_HOST=db
      -_DB_DATABASE=sesc-escola
      -_DB_USERNAME=root
      -_DB_PASSWORD=root
    volumes:
      -.:/var/www
    networks:
      -app-network
    #depends_on:

  nginx:
    build: .docker/nginx
    container_name: servidor-web-nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
